"""initial_schema

Revision ID: 9d5f1c778488
Revises: 
Create Date: 2026-04-20 02:13:07.670794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9d5f1c778488'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('user_profiles')  # managed by Supabase — do not drop
    op.add_column('simulation_results', sa.Column('baseline_transition_matrix_json', sa.JSON(), nullable=True))
    op.add_column('simulation_results', sa.Column('tool_transition_matrix_json', sa.JSON(), nullable=True))
    op.add_column('simulation_results', sa.Column('workflow_diff_json', sa.JSON(), nullable=True))
    op.add_column('tool_evaluations', sa.Column('latest_job_id', sa.String(length=36), nullable=True))
    op.add_column('tool_evaluations', sa.Column('latest_job_status', sa.String(length=20), nullable=True))
    op.add_column('tool_evaluations', sa.Column('latest_job_progress_pct', sa.Integer(), nullable=True))
    op.add_column('tool_evaluations', sa.Column('latest_job_step', sa.Text(), nullable=True))
    op.add_column('tool_evaluations', sa.Column('last_error', sa.Text(), nullable=True))
    op.add_column('tool_evaluations', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'tool_evaluations', 'jobs', ['latest_job_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tool_evaluations', type_='foreignkey')
    op.drop_column('tool_evaluations', 'completed_at')
    op.drop_column('tool_evaluations', 'last_error')
    op.drop_column('tool_evaluations', 'latest_job_step')
    op.drop_column('tool_evaluations', 'latest_job_progress_pct')
    op.drop_column('tool_evaluations', 'latest_job_status')
    op.drop_column('tool_evaluations', 'latest_job_id')
    op.drop_column('simulation_results', 'workflow_diff_json')
    op.drop_column('simulation_results', 'tool_transition_matrix_json')
    op.drop_column('simulation_results', 'baseline_transition_matrix_json')
    op.create_table('user_profiles',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('role', sa.TEXT(), server_default=sa.text("'client'::text"), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('company', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint("role = ANY (ARRAY['admin'::text, 'client'::text])", name=op.f('user_profiles_role_check')),
    sa.ForeignKeyConstraint(['id'], ['auth.users.id'], name=op.f('user_profiles_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('user_profiles_pkey'))
    )
    # ### end Alembic commands ###
